//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg01Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pg01Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;Num9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;Num6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;Num3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;Num5&quot; /&gt;
        ///      &lt;Button X=&quot;8&quot; Y=&quot;8&quot; Key=&quot;Num8&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;ApplicationGroup Name=&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig01 {
            get {
                return ResourceManager.GetString("TestConfig01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;Num9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;Num6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;Num3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;Num5&quot; /&gt;
        ///      &lt;Button X=&quot;8&quot; Y=&quot;8&quot; Key=&quot;Num8&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;ApplicationGroup Name=&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig02 {
            get {
                return ResourceManager.GetString("TestConfig02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;Num9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;Num6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;Num3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;Num5&quot; /&gt;
        ///      &lt;Button X=&quot;8&quot; Y=&quot;8&quot; Key=&quot;Num8&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///    &lt;ButtonsAlignment&gt;Left&lt;/ButtonsAlignment&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;App [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig03 {
            get {
                return ResourceManager.GetString("TestConfig03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;Num9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;Num6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;Num3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;Num5&quot; /&gt;
        ///      &lt;Button X=&quot;8&quot; Y=&quot;8&quot; Key=&quot;Num8&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;ApplicationGroup Name=&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig04 {
            get {
                return ResourceManager.GetString("TestConfig04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;NumPad9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;NumPad6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;NumPad3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;NumPad5&quot; /&gt;
        ///      &lt;Button X=&quot;8&quot; Y=&quot;8&quot; Key=&quot;NumPad8&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;Applicat [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig05 {
            get {
                return ResourceManager.GetString("TestConfig05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;NumPad9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;NumPad6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;NumPad3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;NumPad5&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;ApplicationGroup Name=&quot;CLIP STUDIO PAINT B&quot;&gt;
        ///       [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig06 {
            get {
                return ResourceManager.GetString("TestConfig06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;ResetKey&gt;NumPad5&lt;/ResetKey&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;NumPad9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;NumPad6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;NumPad3&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;ApplicationGroup Name=&quot;CLIP STUDIO PAINT B&quot;&gt;
        ///      &lt;MatchingR [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig07 {
            get {
                return ResourceManager.GetString("TestConfig07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;ResetKey&gt;NumPad5&lt;/ResetKey&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;NumPad9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;NumPad6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;NumPad3&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;ApplicationGroup Name=&quot;CLIP STUDIO PAINT B&quot;&gt;
        ///      &lt;MatchingR [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig08 {
            get {
                return ResourceManager.GetString("TestConfig08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Sample01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;NumPad9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;NumPad6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;NumPad3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;NumPad5&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;0&quot; Y=&quot;0&quot; /&gt;
        ///    &lt;ButtonsAlignment&gt;Left&lt;/ButtonsAlignment&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;Applicat [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig09 {
            get {
                return ResourceManager.GetString("TestConfig09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Sample01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;NumPad9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;NumPad6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;NumPad3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;NumPad5&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;0&quot; Y=&quot;0&quot; /&gt;
        ///    &lt;ButtonsAlignment&gt;Left&lt;/ButtonsAlignment&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;Applicat [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig10 {
            get {
                return ResourceManager.GetString("TestConfig10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;Num9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;Num6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;Num3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;Num5&quot; /&gt;
        ///      &lt;Button X=&quot;8&quot; Y=&quot;8&quot; Key=&quot;Num8&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;ApplicationGroup Name=&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig11 {
            get {
                return ResourceManager.GetString("TestConfig11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Sample12XXXXXXXX&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;0&quot; Key=&quot;NumPad9&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;1&quot; Key=&quot;NumPad6&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;2&quot; Key=&quot;NumPad3&quot; /&gt;
        ///      &lt;Button X=&quot;0&quot; Y=&quot;3&quot; Key=&quot;NumPad5&quot; /&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;0&quot; Y=&quot;0&quot; /&gt;
        ///    &lt;ButtonsAlignment&gt;Left&lt;/ButtonsAlignment&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig12 {
            get {
                return ResourceManager.GetString("TestConfig12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Basic&gt;
        ///    &lt;Title&gt;Title01&lt;/Title&gt;
        ///    &lt;Buttons&gt;
        ///    &lt;/Buttons&gt;
        ///    &lt;WindowLocation X=&quot;99999&quot; Y=&quot;0&quot; /&gt;
        ///  &lt;/Basic&gt;
        ///  &lt;ApplicationGroups&gt;
        ///    &lt;ApplicationGroup Name=&quot;CLIP STUDIO PAINT&quot;&gt;
        ///      &lt;MatchingRoule&gt;
        ///        &lt;ExeName&gt;ClipStudioPaint.exe&lt;/ExeName&gt;
        ///        &lt;WindowTitlePatterns&gt;
        ///          &lt;Pattern&gt;*CLIP STUDIO PAINT&lt;/Pattern&gt;
        ///          &lt;Pattern&gt;ショートカット設定&lt;/Pat [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestConfig13 {
            get {
                return ResourceManager.GetString("TestConfig13", resourceCulture);
            }
        }
    }
}
