//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg01.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pg01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   RadGest01Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IPCPortName {
            get {
                return ResourceManager.GetString("IPCPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに起動しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_Application_Startup_ {
            get {
                return ResourceManager.GetString("MainWindow_Application_Startup_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先行プロセスです。後続プロセスの起動を待機しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_Application_Startup_先行プロセス {
            get {
                return ResourceManager.GetString("MainWindow_Application_Startup_先行プロセス", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyIconconfigItemText {
            get {
                return ResourceManager.GetString("NotifyIconconfigItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyIconExitItemText {
            get {
                return ResourceManager.GetString("NotifyIconExitItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RadGest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyIconText {
            get {
                return ResourceManager.GetString("NotifyIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon PerfCenterCpl {
            get {
                object obj = ResourceManager.GetObject("PerfCenterCpl", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
